{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "n8n-sandbox-service.apiName" . }}
  labels:
    {{- include "n8n-sandbox-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className | quote }}
  {{- end }}
  {{- with .Values.api.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "n8n-sandbox-service.apiName" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
