// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: runner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	HttpBaseUrl   string                 `protobuf:"bytes,2,opt,name=http_base_url,json=httpBaseUrl,proto3" json:"http_base_url,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CapacityTotal int32                  `protobuf:"varint,4,opt,name=capacity_total,json=capacityTotal,proto3" json:"capacity_total,omitempty"`
	CapacityUsed  int32                  `protobuf:"varint,5,opt,name=capacity_used,json=capacityUsed,proto3" json:"capacity_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerHeartbeat) Reset() {
	*x = RunnerHeartbeat{}
	mi := &file_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerHeartbeat) ProtoMessage() {}

func (x *RunnerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerHeartbeat.ProtoReflect.Descriptor instead.
func (*RunnerHeartbeat) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerHeartbeat) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunnerHeartbeat) GetHttpBaseUrl() string {
	if x != nil {
		return x.HttpBaseUrl
	}
	return ""
}

func (x *RunnerHeartbeat) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *RunnerHeartbeat) GetCapacityTotal() int32 {
	if x != nil {
		return x.CapacityTotal
	}
	return 0
}

func (x *RunnerHeartbeat) GetCapacityUsed() int32 {
	if x != nil {
		return x.CapacityUsed
	}
	return 0
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_runner_proto protoreflect.FileDescriptor

const file_runner_proto_rawDesc = "" +
	"\n" +
	"\frunner.proto\x12\trunner.v1\"\xb8\x01\n" +
	"\x0fRunnerHeartbeat\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\"\n" +
	"\rhttp_base_url\x18\x02 \x01(\tR\vhttpBaseUrl\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12%\n" +
	"\x0ecapacity_total\x18\x04 \x01(\x05R\rcapacityTotal\x12#\n" +
	"\rcapacity_used\x18\x05 \x01(\x05R\fcapacityUsed\"\"\n" +
	"\x0eControlMessage\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2V\n" +
	"\x0eRunnerRegistry\x12D\n" +
	"\aConnect\x12\x1a.runner.v1.RunnerHeartbeat\x1a\x19.runner.v1.ControlMessage(\x010\x01B;Z9github.com/n8n-io/sandbox-service/internal/api/grpc/pb;pbb\x06proto3"

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData []byte
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)))
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runner_proto_goTypes = []any{
	(*RunnerHeartbeat)(nil), // 0: runner.v1.RunnerHeartbeat
	(*ControlMessage)(nil),  // 1: runner.v1.ControlMessage
}
var file_runner_proto_depIdxs = []int32{
	0, // 0: runner.v1.RunnerRegistry.Connect:input_type -> runner.v1.RunnerHeartbeat
	1, // 1: runner.v1.RunnerRegistry.Connect:output_type -> runner.v1.ControlMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
