// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: runner.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerRegistry_Connect_FullMethodName = "/runner.v1.RunnerRegistry/Connect"
)

// RunnerRegistryClient is the client API for RunnerRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnerRegistry receives bi-directional streams from sandbox runners.
type RunnerRegistryClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunnerHeartbeat, ControlMessage], error)
}

type runnerRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerRegistryClient(cc grpc.ClientConnInterface) RunnerRegistryClient {
	return &runnerRegistryClient{cc}
}

func (c *runnerRegistryClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunnerHeartbeat, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerRegistry_ServiceDesc.Streams[0], RunnerRegistry_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunnerHeartbeat, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerRegistry_ConnectClient = grpc.BidiStreamingClient[RunnerHeartbeat, ControlMessage]

// RunnerRegistryServer is the server API for RunnerRegistry service.
// All implementations must embed UnimplementedRunnerRegistryServer
// for forward compatibility.
//
// RunnerRegistry receives bi-directional streams from sandbox runners.
type RunnerRegistryServer interface {
	Connect(grpc.BidiStreamingServer[RunnerHeartbeat, ControlMessage]) error
	mustEmbedUnimplementedRunnerRegistryServer()
}

// UnimplementedRunnerRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerRegistryServer struct{}

func (UnimplementedRunnerRegistryServer) Connect(grpc.BidiStreamingServer[RunnerHeartbeat, ControlMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRunnerRegistryServer) mustEmbedUnimplementedRunnerRegistryServer() {}
func (UnimplementedRunnerRegistryServer) testEmbeddedByValue()                        {}

// UnsafeRunnerRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerRegistryServer will
// result in compilation errors.
type UnsafeRunnerRegistryServer interface {
	mustEmbedUnimplementedRunnerRegistryServer()
}

func RegisterRunnerRegistryServer(s grpc.ServiceRegistrar, srv RunnerRegistryServer) {
	// If the following call pancis, it indicates UnimplementedRunnerRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerRegistry_ServiceDesc, srv)
}

func _RunnerRegistry_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerRegistryServer).Connect(&grpc.GenericServerStream[RunnerHeartbeat, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerRegistry_ConnectServer = grpc.BidiStreamingServer[RunnerHeartbeat, ControlMessage]

// RunnerRegistry_ServiceDesc is the grpc.ServiceDesc for RunnerRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.v1.RunnerRegistry",
	HandlerType: (*RunnerRegistryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RunnerRegistry_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "runner.proto",
}
