// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: runner/v1/runner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerHeartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunnerId        string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	HttpBaseUrl     string                 `protobuf:"bytes,2,opt,name=http_base_url,json=httpBaseUrl,proto3" json:"http_base_url,omitempty"`
	Healthy         bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CapacityTotal   int32                  `protobuf:"varint,4,opt,name=capacity_total,json=capacityTotal,proto3" json:"capacity_total,omitempty"`
	CapacityUsed    int32                  `protobuf:"varint,5,opt,name=capacity_used,json=capacityUsed,proto3" json:"capacity_used,omitempty"`
	ControlGrpcAddr string                 `protobuf:"bytes,6,opt,name=control_grpc_addr,json=controlGrpcAddr,proto3" json:"control_grpc_addr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunnerHeartbeat) Reset() {
	*x = RunnerHeartbeat{}
	mi := &file_runner_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerHeartbeat) ProtoMessage() {}

func (x *RunnerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerHeartbeat.ProtoReflect.Descriptor instead.
func (*RunnerHeartbeat) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerHeartbeat) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunnerHeartbeat) GetHttpBaseUrl() string {
	if x != nil {
		return x.HttpBaseUrl
	}
	return ""
}

func (x *RunnerHeartbeat) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *RunnerHeartbeat) GetCapacityTotal() int32 {
	if x != nil {
		return x.CapacityTotal
	}
	return 0
}

func (x *RunnerHeartbeat) GetCapacityUsed() int32 {
	if x != nil {
		return x.CapacityUsed
	}
	return 0
}

func (x *RunnerHeartbeat) GetControlGrpcAddr() string {
	if x != nil {
		return x.ControlGrpcAddr
	}
	return ""
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_runner_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CreateJson    string                 `protobuf:"bytes,2,opt,name=create_json,json=createJson,proto3" json:"create_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_runner_v1_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxRequest) GetCreateJson() string {
	if x != nil {
		return x.CreateJson
	}
	return ""
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	ContainerIp   string                 `protobuf:"bytes,2,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_runner_v1_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

type StopSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_runner_v1_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{4}
}

func (x *StopSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StopSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxResponse) Reset() {
	*x = StopSandboxResponse{}
	mi := &file_runner_v1_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxResponse) ProtoMessage() {}

func (x *StopSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxResponse.ProtoReflect.Descriptor instead.
func (*StopSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{5}
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_runner_v1_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type DeleteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxResponse) Reset() {
	*x = DeleteSandboxResponse{}
	mi := &file_runner_v1_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxResponse) ProtoMessage() {}

func (x *DeleteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxResponse.ProtoReflect.Descriptor instead.
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{7}
}

var File_runner_v1_runner_proto protoreflect.FileDescriptor

const file_runner_v1_runner_proto_rawDesc = "" +
	"\n" +
	"\x16runner/v1/runner.proto\x12\trunner.v1\"\xe4\x01\n" +
	"\x0fRunnerHeartbeat\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\"\n" +
	"\rhttp_base_url\x18\x02 \x01(\tR\vhttpBaseUrl\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12%\n" +
	"\x0ecapacity_total\x18\x04 \x01(\x05R\rcapacityTotal\x12#\n" +
	"\rcapacity_used\x18\x05 \x01(\x05R\fcapacityUsed\x12*\n" +
	"\x11control_grpc_addr\x18\x06 \x01(\tR\x0fcontrolGrpcAddr\"\"\n" +
	"\x0eControlMessage\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"V\n" +
	"\x14CreateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vcreate_json\x18\x02 \x01(\tR\n" +
	"createJson\"Y\n" +
	"\x15CreateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12!\n" +
	"\fcontainer_ip\x18\x02 \x01(\tR\vcontainerIp\"3\n" +
	"\x12StopSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x15\n" +
	"\x13StopSandboxResponse\"5\n" +
	"\x14DeleteSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x17\n" +
	"\x15DeleteSandboxResponse2V\n" +
	"\x0eRunnerRegistry\x12D\n" +
	"\aConnect\x12\x1a.runner.v1.RunnerHeartbeat\x1a\x19.runner.v1.ControlMessage(\x010\x012\x86\x02\n" +
	"\x0eSandboxControl\x12R\n" +
	"\rCreateSandbox\x12\x1f.runner.v1.CreateSandboxRequest\x1a .runner.v1.CreateSandboxResponse\x12L\n" +
	"\vStopSandbox\x12\x1d.runner.v1.StopSandboxRequest\x1a\x1e.runner.v1.StopSandboxResponse\x12R\n" +
	"\rDeleteSandbox\x12\x1f.runner.v1.DeleteSandboxRequest\x1a .runner.v1.DeleteSandboxResponseB;Z9github.com/n8n-io/sandbox-service/internal/api/grpc/pb;pbb\x06proto3"

var (
	file_runner_v1_runner_proto_rawDescOnce sync.Once
	file_runner_v1_runner_proto_rawDescData []byte
)

func file_runner_v1_runner_proto_rawDescGZIP() []byte {
	file_runner_v1_runner_proto_rawDescOnce.Do(func() {
		file_runner_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_v1_runner_proto_rawDesc), len(file_runner_v1_runner_proto_rawDesc)))
	})
	return file_runner_v1_runner_proto_rawDescData
}

var file_runner_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_runner_v1_runner_proto_goTypes = []any{
	(*RunnerHeartbeat)(nil),       // 0: runner.v1.RunnerHeartbeat
	(*ControlMessage)(nil),        // 1: runner.v1.ControlMessage
	(*CreateSandboxRequest)(nil),  // 2: runner.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil), // 3: runner.v1.CreateSandboxResponse
	(*StopSandboxRequest)(nil),    // 4: runner.v1.StopSandboxRequest
	(*StopSandboxResponse)(nil),   // 5: runner.v1.StopSandboxResponse
	(*DeleteSandboxRequest)(nil),  // 6: runner.v1.DeleteSandboxRequest
	(*DeleteSandboxResponse)(nil), // 7: runner.v1.DeleteSandboxResponse
}
var file_runner_v1_runner_proto_depIdxs = []int32{
	0, // 0: runner.v1.RunnerRegistry.Connect:input_type -> runner.v1.RunnerHeartbeat
	2, // 1: runner.v1.SandboxControl.CreateSandbox:input_type -> runner.v1.CreateSandboxRequest
	4, // 2: runner.v1.SandboxControl.StopSandbox:input_type -> runner.v1.StopSandboxRequest
	6, // 3: runner.v1.SandboxControl.DeleteSandbox:input_type -> runner.v1.DeleteSandboxRequest
	1, // 4: runner.v1.RunnerRegistry.Connect:output_type -> runner.v1.ControlMessage
	3, // 5: runner.v1.SandboxControl.CreateSandbox:output_type -> runner.v1.CreateSandboxResponse
	5, // 6: runner.v1.SandboxControl.StopSandbox:output_type -> runner.v1.StopSandboxResponse
	7, // 7: runner.v1.SandboxControl.DeleteSandbox:output_type -> runner.v1.DeleteSandboxResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_v1_runner_proto_init() }
func file_runner_v1_runner_proto_init() {
	if File_runner_v1_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_v1_runner_proto_rawDesc), len(file_runner_v1_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runner_v1_runner_proto_goTypes,
		DependencyIndexes: file_runner_v1_runner_proto_depIdxs,
		MessageInfos:      file_runner_v1_runner_proto_msgTypes,
	}.Build()
	File_runner_v1_runner_proto = out.File
	file_runner_v1_runner_proto_goTypes = nil
	file_runner_v1_runner_proto_depIdxs = nil
}
